// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLQsEvUBF2ckIyHwl6VNx8yDfnZ8zGEGE',
    appId: '1:624301065858:web:4284898bfb1676faeb969b',
    messagingSenderId: '624301065858',
    projectId: 'project-5442431422660328081',
    authDomain: 'project-5442431422660328081.firebaseapp.com',
    storageBucket: 'project-5442431422660328081.firebasestorage.app',
    measurementId: 'G-SM49SXHF4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuFeAPoTmjCU-UChL8PEOaMrBhJ3K94-I',
    appId: '1:624301065858:android:641aa074ae5ad976eb969b',
    messagingSenderId: '624301065858',
    projectId: 'project-5442431422660328081',
    storageBucket: 'project-5442431422660328081.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLQsEvUBF2ckIyHwl6VNx8yDfnZ8zGEGE',
    appId: '1:624301065858:web:e255e0d290644c35eb969b',
    messagingSenderId: '624301065858',
    projectId: 'project-5442431422660328081',
    authDomain: 'project-5442431422660328081.firebaseapp.com',
    storageBucket: 'project-5442431422660328081.firebasestorage.app',
    measurementId: 'G-CZ1CT05G8K',
  );
}
